### ISSUE TITLE
RespondList

### ISSUE THREAD

**Issue by shenxwang** [torchbox/m-response#156]
### RespondList
**(Page name is matccing with the artboard name in Zeplin)**

@abigail-hampson
- [ ] 1. The spacing between the title and edge of the screen.
- [ ] 2. The height of the red line(2px), Radius of the rectangle (4).
- [ ] 3. Text style of the users' name, and spacing between the edge and the star. The size & spacing of the star. The size & spacing of the product logo.
- [ ] 4. Text style of the users' device, and spacing to the edge of the rectangle. 
- [ ] 5. Text style of the description, and spacing to the edge of the rectangle. The style of publishing date and spacing to the edge of the rectangle.
- [ ] 6. Size of the button, Text style of the button text, and spacing between the button and other elements.
- [ ] 7. Text style of the text button, and spacing between the button and other elements.
- [ ] 8. Spacing with button and next review.
- [ ] 9. No red highlight for next review. (The hight only shows on the current card.)
![respondlist](https://user-images.githubusercontent.com/44074748/47274042-fa75ab80-d56c-11e8-811a-3fa1466f5010.png)

**Comment by shenxwang** [comment]
@abigail-hampson @NathHorrigan 
- [ ] 1. The spacing between the title and other elements.
- [ ] 2. The shadow of the card. (#000000 A10%, 0x 0y 2blur 0spread)
- [ ] 3.  The size of the product logo.
- [ ] 4. Text style of the users' device (caption8). 
- [ ] 5. The spacing between stars and review text.
- [ ] 6. Text style of the date (caption8). 
- [ ] 7. Text style of the button and the text button. Shadow of the button. (#000000 A10%, 0x 4y 1
![respondlist1](https://user-images.githubusercontent.com/44074748/47461865-d655dc80-d7af-11e8-8683-3cf5f626b9dd.png)
2blur 0spread)

**Comment by NathHorrigan** [comment]
@shenxwang Fixes are now on staging

**Comment by shenxwang** [comment]
@NathHorrigan Thank you for working on that. It looks great.
There are only few detail might need to fix. 
- [ ] 1. The spacing between the title and the card (8px).
- [ ] 2. The spacing between the stars and the text (12px).
- [ ] 3.  The text style of the caption text (Open sans regular #737373).
- [ ] 4.  The text style of the button (bold).
![image](https://user-images.githubusercontent.com/44074748/47505770-c59f7800-d83c-11e8-88c2-f1049318f001.png)

**Comment by NathHorrigan** [comment]
@shenxwang Can you please you're looking at the changes on the staging site and not prod.
